owner: koj-co
repo: upptime
user-agent: KojBot
sites:
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Internet Archive
    url: https://archive.org
  - name: Hacker News
    url: https://news.ycombinator.com
  - name: Broken Site
    url: https://thissitedoesnotexist.com
assignees:
  - AnandChowdhary
status-website:
  cname: upptime.js.org
  logoUrl: https://avatars3.githubusercontent.com/u/65495851?s=88&v=4
  name: Koj Status
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [Github repository](https://github.com/koj-co/upptime). Literally, no server required, it's just GitHub Actions, Issues, and Pages.
