owner: koj-co
repo: status
sites:
  - name: Koj.co
    url: https://koj.co
  - name: Koj CDN
    url: https://kojcdn.com
  - name: URL Shortener
    url: https://go.koj.co
  - name: Koj Status
    url: https://status.koj.co
  - name: Koj Analytics
    url: https://analytics.koj.co
  - name: Koj API
    url: https://api.koj.co
assignees:
  - AnandChowdhary
