name: Response Time CI
on:
  schedule:
    - cron: "*/30 * * * *"
jobs:
  release:
    name: Check status
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: npm ci
      - name: Run script
        run: npm run update-with-commit
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
